# Generated by Django 5.2.7 on 2025-10-09 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("first_visit", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("total_analyses", models.IntegerField(default=0)),
                ("device_info", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="VideoAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_url", models.URLField(max_length=500)),
                (
                    "video_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("title", models.CharField(max_length=500)),
                ("duration", models.CharField(max_length=20)),
                ("thumbnail_url", models.URLField(max_length=500)),
                ("highlights", models.JSONField()),
                ("analysis_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_status",
                    models.CharField(default="completed", max_length=20),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["video_id"], name="analysis_ap_video_i_de0b43_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="analysis_ap_created_3fb2ba_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VideoBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100)),
                ("bookmarked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis_api.videoanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["-bookmarked_at"],
                "unique_together": {("session_id", "video_analysis")},
            },
        ),
    ]
