# Generated by Django 5.2.7 on 2025-10-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoanalysis",
            name="device_id",
            field=models.CharField(
                db_index=True, default="legacy-device", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="videoanalysis",
            name="video_id",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="videoanalysis",
            unique_together={("device_id", "video_id")},
        ),
        migrations.AddIndex(
            model_name="videoanalysis",
            index=models.Index(
                fields=["device_id"], name="analysis_ap_device__2cdaa7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videoanalysis",
            index=models.Index(
                fields=["device_id", "video_id"], name="analysis_ap_device__351acf_idx"
            ),
        ),
    ]
